### ISSUE TITLE
Status incorrect

### ISSUE THREAD

**Issue by TinoM** [widelands/bunnybot#2]
=> https://code.launchpad.net/~widelands-dev/widelands/bug-1397500/+merge/243860/comments/722213

This message was generated the moment Appveyor succeeded.
Two problems:
- The state of Travis is announced as "failed", but it was still working. Better would be "created" or "running".
- If Bunnybot always announces both states together, it should only do this when both jobs are finished.

**Comment by SirVer** [comment]
Agreed to all points, just one to add: if travis was okay, then in progress while appveyor finishes (without changing state) and then is okay again, the same state should not be reported again.

**Comment by SirVer** [comment]
This has been implemented with the rust rewrite a while ago.
